use crate::error::InvalidUpdateError;
use std::sync::Arc;

/// State trait for graph state management
///
/// All states used in Juncture graphs must implement this trait.
/// The #[derive(State)] macro automatically generates the implementation.
pub trait State: Clone + Send + Sync + std::fmt::Debug + 'static {
    /// Partial update type generated by #[derive(State)]
    type Update: Default + Clone + Send + Sync + 'static;

    /// Field version tracking type
    type FieldVersions: Default + Clone + Send + Sync + std::fmt::Debug + 'static;

    /// Apply an update to this state, returning which fields changed
    fn apply(&mut self, update: Self::Update) -> FieldsChanged;

    /// Apply an update to this state, returning which fields changed or an error
    ///
    /// Unlike `apply()`, this method returns a structured error when reducer
    /// constraints are violated (e.g., multiple writers on a replace channel).
    /// The default implementation delegates to `apply()` for backward compatibility.
    ///
    /// # Errors
    ///
    /// Returns `InvalidUpdateError` if the update violates reducer constraints,
    /// such as `InvalidUpdateError::MultipleOverwrite` when multiple nodes
    /// write to a replace channel in the same superstep.
    fn try_apply(&mut self, update: Self::Update) -> Result<FieldsChanged, InvalidUpdateError> {
        Ok(self.apply(update))
    }

    /// Reset ephemeral fields (called after each superstep)
    fn reset_ephemeral(&mut self);

    /// Finish a specific field (called when graph execution completes)
    ///
    /// This allows channels to finalize their state. For example,
    /// `LastValueAfterFinishChannel` only makes its value available after
    /// `finish()` is called.
    ///
    /// Default implementation is a no-op for channels that don't need finish semantics.
    fn finish_field(&mut self, _field_idx: usize) {}

    /// Get current field versions (owned copy).
    ///
    /// Versions are managed by `PregelLoop` via its own `FieldVersionTracker`.
    /// This method returns a snapshot for checkpoint serialization.
    #[must_use]
    fn field_versions(&self) -> Self::FieldVersions {
        Self::FieldVersions::default()
    }

    /// Bump versions for changed fields.
    ///
    /// Default is a no-op: `PregelLoop` manages versions in its own
    /// `FieldVersionTracker` rather than inside the `State` struct.
    fn bump_versions(&mut self, _changed: &FieldsChanged) {}

    /// Schema version for migration
    #[must_use]
    fn schema_version() -> u32 {
        1
    }

    /// Migrate from older schema version
    #[must_use]
    fn migrate(_from_version: u32, value: serde_json::Value) -> serde_json::Value {
        value
    }
}

/// Bitmask tracking which fields changed
///
/// Uses `u64` to track up to 64 fields. For states with more fields,
/// enable the "wide-state" feature to use `FixedBitSet` instead.
#[derive(Clone, Debug, Default)]
pub struct FieldsChanged(pub u64);

impl FieldsChanged {
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.0 == 0
    }

    #[must_use]
    pub const fn has_field(&self, index: usize) -> bool {
        self.0 & (1 << index) != 0
    }

    #[allow(
        clippy::missing_const_for_fn,
        reason = "mutable methods cannot be const"
    )]
    pub fn set_field(&mut self, index: usize) {
        self.0 |= 1 << index;
    }

    #[allow(
        clippy::missing_const_for_fn,
        reason = "mutable methods cannot be const"
    )]
    pub fn merge(&mut self, other: &Self) {
        self.0 |= other.0;
    }
}

/// Copy-on-write state wrapper (default state wrapper)
///
/// For large states (e.g., long conversation histories), cloning the entire
/// state for each node spawn is expensive. `CowState` uses `Arc` to share
/// immutable state and only clones when modified.
///
/// This is the DEFAULT state wrapper in Juncture, not just an optimization.
#[derive(Debug)]
pub struct CowState<S: State> {
    /// Shared immutable state
    shared: Arc<S>,
    /// Pending local modifications
    pending: Option<S::Update>,
}

impl<S: State> CowState<S> {
    /// Create `CowState` from shared state
    #[must_use]
    pub const fn new(state: Arc<S>) -> Self {
        Self {
            shared: state,
            pending: None,
        }
    }

    /// Get current state (read-only)
    pub fn get(&self) -> &S {
        &self.shared
    }

    /// Get mutable access to the state, cloning the inner Arc if shared
    ///
    /// Uses clone-on-write semantics: if the Arc reference count is greater
    /// than one, the inner state is cloned before returning a mutable reference.
    /// This ensures no other `CowState` instances are affected by mutations.
    pub fn get_mut(&mut self) -> &mut S
    where
        S: Clone,
    {
        Arc::make_mut(&mut self.shared)
    }

    /// Apply an update (deferred until commit)
    ///
    /// Note: For proper merge semantics, this implementation simply stores
    /// the latest update. The proc-macro generates more sophisticated
    /// merge logic for complex update types.
    pub fn update(&mut self, changes: S::Update) {
        // Store the new update, replacing any previous pending update
        // The State trait's apply() method handles proper merging when commit() is called
        self.pending = Some(changes);
    }

    /// Commit updates and return new shared state
    pub fn commit(self) -> Arc<S> {
        if let Some(pending) = self.pending {
            let mut state = (*self.shared).clone();
            state.apply(pending);
            Arc::new(state)
        } else {
            self.shared
        }
    }

    /// Commit updates and return new shared state, propagating reducer errors
    ///
    /// Unlike `commit()`, this method returns a structured error when reducer
    /// constraints are violated (e.g., multiple writers on a replace channel).
    ///
    /// # Errors
    ///
    /// Returns `InvalidUpdateError` if the update violates reducer constraints.
    pub fn try_commit(self) -> Result<Arc<S>, InvalidUpdateError> {
        if let Some(pending) = self.pending {
            let mut state = (*self.shared).clone();
            let _changed = state.try_apply(pending)?;
            Ok(Arc::new(state))
        } else {
            Ok(self.shared)
        }
    }
}

impl<S: State> Clone for CowState<S> {
    fn clone(&self) -> Self {
        Self {
            shared: Arc::clone(&self.shared),
            pending: None,
        }
    }
}

impl<S: State> std::ops::Deref for CowState<S> {
    type Target = S;

    fn deref(&self) -> &Self::Target {
        &self.shared
    }
}

/// Trait for converting input schema into full State
pub trait IntoState<S: State>: Clone + Send + Sync + 'static {
    fn into_state(self) -> S;
}

/// Trait for extracting output schema from full State
pub trait FromState<S: State>: Clone + Send + Sync + 'static {
    fn from_state(state: &S) -> Self;
}

// Rust guideline compliant 2025-01-18
